export default [
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico",
        "height": 1008,
        "highlighted": false,
        "id": 574,
        "incognito": false,
        "index": 0,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Building a Chrome Extension Using React | by Gil Fink | Medium",
        "url": "https://medium.com/@gilfink/building-a-chrome-extension-using-react-c5bfe45aaf36",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": true,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/5068772e/img/favicon_32.png",
        "height": 1008,
        "highlighted": false,
        "id": 618,
        "incognito": false,
        "index": 1,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "The Dark Knight Trilogy Definitive Cut - YouTube",
        "url": "https://www.youtube.com/watch?v=t1J55LVUYhg",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "",
        "height": 1008,
        "highlighted": false,
        "id": 640,
        "incognito": false,
        "index": 2,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Extensions",
        "url": "chrome://extensions/",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 1819,
        "incognito": false,
        "index": 3,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#method-get",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 1871,
        "incognito": false,
        "index": 4,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#method-query",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 1946,
        "incognito": false,
        "index": 5,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#type-TabStatus",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1846,
        "incognito": false,
        "index": 6,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Building a Chrome Extension Using React | by Gil Fink | Medium",
        "url": "https://medium.com/@gilfink/building-a-chrome-extension-using-react-c5bfe45aaf36",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 1008,
        "highlighted": false,
        "id": 1933,
        "incognito": false,
        "index": 7,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "ProfessorX737/react-sortablejs: A React component built on top of the mature drag and drop library, Sortable.",
        "url": "https://github.com/ProfessorX737/react-sortablejs",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
        "height": 1008,
        "highlighted": false,
        "id": 1936,
        "incognito": false,
        "index": 8,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer - npm",
        "url": "https://www.npmjs.com/package/puppeteer",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "http://localhost:3001/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1940,
        "incognito": false,
        "index": 9,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "React App",
        "url": "http://localhost:3001/",
        "width": 1078,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 143,
        "incognito": false,
        "index": 0,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "turtle nusery rouse hill - Google Search",
        "url": "https://www.google.com/search?q=turtle+nusery+rouse+hill&oq=turtle+nusery+rouse+hill&aqs=chrome..69i57j46.10264j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.turtlenursery.com.au/wp-content/uploads/2017/10/t-logo-100x100.png",
        "height": 981,
        "highlighted": false,
        "id": 149,
        "incognito": false,
        "index": 1,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Paver Supplies | Bricks, Block and Paver Suppliers, Supply in Sydney",
        "url": "https://www.turtlenursery.com.au/bricks-blocks/",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 981,
        "highlighted": false,
        "id": 232,
        "incognito": false,
        "index": 2,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "ProfessorX737/react-sortablejs: A React component built on top of the mature drag and drop library, Sortable.",
        "url": "https://github.com/ProfessorX737/react-sortablejs",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 981,
        "highlighted": false,
        "id": 235,
        "incognito": false,
        "index": 3,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "SortableJS/Sortable: Sortable — is a JavaScript library for reorderable drag-and-drop lists on modern browsers and touch devices. No jQuery required. Supports Meteor, AngularJS, React, Polymer, Vue, Ember, Knockout and any CSS library, e.g. Bootstrap.",
        "url": "https://github.com/SortableJS/Sortable",
        "width": 1848,
        "windowId": 144
    },
]
/*
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 350,
        "incognito": false,
        "index": 4,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome take screenshot of webpage react - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk01CiRCnAIv9Lanh4P1hRS20sba3pw%3A1599047641978&ei=2YdPX9GoO5aR9QP4rKS4Dw&q=chrome+take+screenshot+of+webpage+react&oq=chrome+take+screenshot+of+webpage+react&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgATIHCCEQChCgAToHCAAQRxCwAzoGCAAQFhAeOggIIRAWEB0QHlCcUViUVmDnVmgAcAB4AIAB1wKIAc4LkgEFMi0zLjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwiR-bbVtMrrAhWWSH0KHXgWCfcQ4dUDCA0&uact=5",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.zapier.com/zapier/images/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 353,
        "incognito": false,
        "index": 5,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "How to Take a Full-Page Screenshot",
        "url": "https://zapier.com/blog/full-page-screenshots-in-chrome/",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 356,
        "incognito": false,
        "index": 6,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "📷 How to take a screenshot of a webpage with JavaScript in Node.js (using puppeteer) - DEV",
        "url": "https://dev.to/benjaminmock/how-to-take-a-screenshot-of-a-page-with-javascript-1e7c",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://buddy.works/assets/icons/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 359,
        "incognito": false,
        "index": 7,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "How to take screenshots with Puppeteer | Buddy: The DevOps Automation Platform",
        "url": "https://buddy.works/guides/how-take-screenshots-with-puppeteer-headless-chrome",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 362,
        "incognito": false,
        "index": 8,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer screenshot - Google Search",
        "url": "https://www.google.com/search?q=puppeteer+screenshot&oq=puppeteer+screenshot&aqs=chrome.0.69i59j0l5j69i60l2.2317j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://pptr.dev/favicons/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 365,
        "incognito": false,
        "index": 9,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Browser",
        "url": "https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-class-browser",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico",
        "height": 981,
        "highlighted": false,
        "id": 368,
        "incognito": false,
        "index": 10,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "How to take screenshots using Puppeteer | by Dishant Agnihotri | Medium",
        "url": "https://medium.com/@dishantagnihotri/how-to-take-screenshots-using-puppeteer-79d18157ed0d",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/b8a6decb/img/favicon_32.png",
        "height": 981,
        "highlighted": false,
        "id": 377,
        "incognito": false,
        "index": 11,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer javascript - YouTube",
        "url": "https://www.youtube.com/results?search_query=puppeteer+javascript",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/b8a6decb/img/favicon_32.png",
        "height": 981,
        "highlighted": false,
        "id": 380,
        "incognito": false,
        "index": 12,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Web automation with JavaScript for beginners | Puppeteer - YouTube",
        "url": "https://www.youtube.com/watch?v=wqRKEd0_suw",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/b8a6decb/img/favicon_32.png",
        "height": 981,
        "highlighted": false,
        "id": 383,
        "incognito": false,
        "index": 13,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Automated Form Submissions with Chrome Puppeteer & NodeJS - YouTube",
        "url": "https://www.youtube.com/watch?v=6IOrp8HgnJU",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 386,
        "incognito": false,
        "index": 14,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer embed browser - Google Search",
        "url": "https://www.google.com/search?q=puppeteer+embed+browser&oq=puppeteer+embed+browser&aqs=chrome..69i57.10314j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
        "height": 981,
        "highlighted": false,
        "id": 389,
        "incognito": false,
        "index": 15,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer-extensionbridge - npm",
        "url": "https://www.npmjs.com/package/puppeteer-extensionbridge",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
        "height": 981,
        "highlighted": false,
        "id": 426,
        "incognito": false,
        "index": 16,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "npm",
        "url": "https://www.npmjs.com/~jsoverson",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.gstatic.com/devrel-devsite/prod/v425077d6c7be97246d05a953898cb9591a173a3cef753a451b8729896196bc0a/developers/images/favicon.png",
        "height": 981,
        "highlighted": false,
        "id": 392,
        "incognito": false,
        "index": 17,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Puppeteer  |  Tools for Web Developers  |  Google Developers",
        "url": "https://developers.google.com/web/tools/puppeteer",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "http://thecodebarbarian.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 395,
        "incognito": false,
        "index": 18,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Control Chrome from Node.js with Puppeteer | www.thecodebarbarian.com",
        "url": "http://thecodebarbarian.com/control-chrome-from-node-js-with-puppeteer.html",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": true,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 981,
        "highlighted": true,
        "id": 457,
        "incognito": false,
        "index": 19,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": true,
        "status": "complete",
        "title": "Content Scripts - Google Chrome",
        "url": "https://developer.chrome.com/extensions/content_scripts",
        "width": 1848,
        "windowId": 144
    }
]
*/