export default [
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico",
        "height": 1008,
        "highlighted": false,
        "id": 574,
        "incognito": false,
        "index": 0,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Building a Chrome Extension Using React | by Gil Fink | Medium",
        "url": "https://medium.com/@gilfink/building-a-chrome-extension-using-react-c5bfe45aaf36",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/5068772e/img/favicon_32.png",
        "height": 1008,
        "highlighted": false,
        "id": 618,
        "incognito": false,
        "index": 1,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "The Dark Knight Trilogy Adrenaline Cut - YouTube",
        "url": "https://www.youtube.com/watch?v=oR0LpETW_-U",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "",
        "height": 1008,
        "highlighted": false,
        "id": 640,
        "incognito": false,
        "index": 2,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Extensions",
        "url": "chrome://extensions/",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 1819,
        "incognito": false,
        "index": 3,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#event-onActivated",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 1871,
        "incognito": false,
        "index": 4,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#type-Tab",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 1946,
        "incognito": false,
        "index": 5,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#type-TabStatus",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1846,
        "incognito": false,
        "index": 6,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Building a Chrome Extension Using React | by Gil Fink | Medium",
        "url": "https://medium.com/@gilfink/building-a-chrome-extension-using-react-c5bfe45aaf36",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 1008,
        "highlighted": false,
        "id": 1933,
        "incognito": false,
        "index": 7,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "ProfessorX737/react-sortablejs: A React component built on top of the mature drag and drop library, Sortable.",
        "url": "https://github.com/ProfessorX737/react-sortablejs",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
        "height": 1008,
        "highlighted": false,
        "id": 1936,
        "incognito": false,
        "index": 8,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer - npm",
        "url": "https://www.npmjs.com/package/puppeteer",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "http://localhost:3001/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2200,
        "incognito": false,
        "index": 9,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "React App",
        "url": "http://localhost:3001/",
        "width": 1242,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://ssl.gstatic.com/docs/doclist/images/infinite_arrow_favicon_5.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1955,
        "incognito": false,
        "index": 10,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "TabsCollage - Google Drive",
        "url": "https://drive.google.com/drive/u/0/folders/1pNbUN13bNUVsurQVieNfrwpn3wc_x7V9",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://ssl.gstatic.com/docs/documents/images/kix-favicon7.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1965,
        "incognito": false,
        "index": 11,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Plan - Google Docs",
        "url": "https://docs.google.com/document/d/1er1xtU2KMNFwCjSQTNzuB5nf9lrOGU2PJbdKq1I9jq4/edit",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://ssl.gstatic.com/docs/documents/images/kix-favicon7.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1958,
        "incognito": false,
        "index": 12,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "shrug assignment - Google Docs",
        "url": "https://docs.google.com/document/d/17GdYADeu6UllKxr2XbvyEeCjE7ASlybHd_ebiLEOInY/edit",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 1972,
        "incognito": false,
        "index": 13,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript regex group match - Google Search",
        "url": "https://www.google.com/search?q=javascript+regex+group+match&oq=javascript+regex+group+match&aqs=chrome.0.0l8.13534j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://javascript.info/img/favicon/favicon.png",
        "height": 1008,
        "highlighted": false,
        "id": 1975,
        "incognito": false,
        "index": 14,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Capturing groups",
        "url": "https://javascript.info/regexp-groups",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 1981,
        "incognito": false,
        "index": 15,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - Regular Expression - Extract subdomain & domain - Stack Overflow",
        "url": "https://stackoverflow.com/questions/25703360/regular-expression-extract-subdomain-domain",
        "width": 1920,
        "windowId": 1
    },
]
/*
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 1990,
        "incognito": false,
        "index": 16,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "JavaScript Array to Set - Stack Overflow",
        "url": "https://stackoverflow.com/questions/28965112/javascript-array-to-set",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://developer.mozilla.org/static/img/favicon32.7f3da72dcea1.png",
        "height": 1008,
        "highlighted": false,
        "id": 1998,
        "incognito": false,
        "index": 17,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Set.prototype.delete() - JavaScript | MDN",
        "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/delete",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2003,
        "incognito": false,
        "index": 18,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - Redux initial state gets mutated even when using Object.assign - Stack Overflow",
        "url": "https://stackoverflow.com/questions/53390498/redux-initial-state-gets-mutated-even-when-using-object-assign",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2006,
        "incognito": false,
        "index": 19,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "react deepCopy object - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk037ZNMHc7ITuC4rDSLqSkLW-3NJMg%3A1599141798589&ei=pvdQX9XBI4ngrQGahoDQBw&q=react+deepCopy+object&oq=react+deepCopy+object&gs_lcp=CgZwc3ktYWIQAzIECAAQDTIGCAAQFhAeMgYIABAWEB46BwgAEEcQsAM6BAgjECc6BQgAEJECOggIABCxAxCDAToFCAAQsQM6CwguELEDEMcBEKMCOgIILjoECAAQQzoLCAAQsQMQgwEQkQI6AggAOgcIABAUEIcCOgQIABAKOggIABAWEAoQHjoICAAQCBANEB5Qt4cDWKymA2DspgNoAXAAeACAAesBiAGeHJIBBjEuMTkuMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjVrOa2k83rAhUJcCsKHRoDAHoQ4dUDCA0&uact=5",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2013,
        "incognito": false,
        "index": 20,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - Deepcopy in React - Stack Overflow",
        "url": "https://stackoverflow.com/questions/39241046/deepcopy-in-react/42018833",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.programmersought.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2019,
        "incognito": false,
        "index": 21,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Basic use of the immutability-helper plugin (with source code) - Programmer Sought",
        "url": "https://www.programmersought.com/article/3332471452/",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2022,
        "incognito": false,
        "index": 22,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "display icon javascript - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk016cRXbSvsMz6Wbxq2WbPoYMaZr4g%3A1599144993992&ei=IQRRX5mePMXe9QPawJqADw&q=display+icon+javascript&oq=display+icon+java&gs_lcp=CgZwc3ktYWIQAxgAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoHCAAQRxCwAzoECCMQJzoECAAQQzoFCAAQkQI6CwguELEDEMcBEKMCOggIABCxAxCDAToHCAAQsQMQQzoFCAAQsQM6BwgAELEDEAo6AggAOgcIABAUEIcCUPtZWPJ2YM6DAWgDcAB4AIABygGIAf4XkgEGMC4xOC4xmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/ebcf1b0f/img/favicon_32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2099,
        "incognito": false,
        "index": 23,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "YouTube",
        "url": "https://www.youtube.com/feed/history",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/ebcf1b0f/img/favicon_32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2118,
        "incognito": false,
        "index": 24,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Web automation with JavaScript for beginners | Puppeteer - YouTube",
        "url": "https://www.youtube.com/watch?v=wqRKEd0_suw&t=613s&ab_channel=HiteshChoudhary",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2121,
        "incognito": false,
        "index": 25,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "react puppeteer tutorial - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk02Nm2iMZbxZUiyKVz7g01iWxkOlog%3A1599192316759&ei=_LxRX5r6LcG_9QOA8L_QCA&q=react+puppeteer+tutorial&oq=react+puppeteer+tutorial&gs_lcp=CgZwc3ktYWIQAzIGCAAQFhAeOgcIABBHELADOgQIIxAnOgIIADoECAAQQzoHCCMQ6gIQJzoHCC4Q6gIQJzoHCAAQsQMQQzoKCAAQsQMQFBCHAjoHCAAQFBCHAjoFCAAQsQM6BQghEKABOggIABAWEAoQHjoHCCMQsAIQJzoECAAQDToGCAAQDRAeOggIABAIEA0QHlDI0gNY9JkEYK6bBGgFcAB4BYAB1gGIAasqkgEGMC4yOS4zmAEAoAEBqgEHZ3dzLXdperABCsABAQ&sclient=psy-ab&ved=0ahUKEwia6N7Pz87rAhXBX30KHQD4D4oQ4dUDCA0&uact=5",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2127,
        "incognito": false,
        "index": 26,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - How to make Puppeteer work with a ReactJS application on the client-side - Stack Overflow",
        "url": "https://stackoverflow.com/questions/55031823/how-to-make-puppeteer-work-with-a-reactjs-application-on-the-client-side/55049611",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 1008,
        "highlighted": false,
        "id": 2130,
        "incognito": false,
        "index": 27,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Trying to install puppeteer inside React app · Issue #3343 · puppeteer/puppeteer",
        "url": "https://github.com/puppeteer/puppeteer/issues/3343",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 1008,
        "highlighted": false,
        "id": 2133,
        "incognito": false,
        "index": 28,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Module not found error can't resolve 'ws' in puppeteer-core/lib · Issue #3466 · puppeteer/puppeteer",
        "url": "https://github.com/puppeteer/puppeteer/issues/3466",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2140,
        "incognito": false,
        "index": 29,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer client side - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk02q10zX2XUAhvJQ8rgbTSN1wfe_lA%3A1599192984958&ei=mL9RX8qOOsaC4-EP_vOj0AQ&q=puppeteer+client+side&oq=puppeteer+client+side&gs_lcp=CgZwc3ktYWIQAzICCAA6BAgjECc6BQgAEJECOgUIABCxAzoICAAQsQMQgwE6CwguELEDEMcBEKMCOgIILjoECAAQQzoECC4QQzoHCAAQsQMQQzoHCAAQFBCHAjoGCAAQFhAeULFhWLuRAWCPkgFoAHAAeACAAdUBiAGdGZIBBjAuMTkuMZgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjKuq6O0s7rAhVGwTgGHf75CEoQ4dUDCA0&uact=5",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.gstatic.com/devrel-devsite/prod/v024eef4ea86c0379222e27415e1e58a21ab1695c99975204bbd5279577b49303/developers/images/favicon.png",
        "height": 1008,
        "highlighted": false,
        "id": 2154,
        "incognito": false,
        "index": 30,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Headless Chrome: an answer to server-side rendering JS sites",
        "url": "https://developers.google.com/web/tools/puppeteer/articles/ssr",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2165,
        "incognito": false,
        "index": 31,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "webpack config externals require is not defined - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk01HURvINIRKD5c3omN7fD1Rtg7GDA%3A1599193506422&ei=osFRX5OrGafZz7sP_tuE8Ag&q=webpack+config+externals+require+is+not+defined&oq=webpack+config+externals+require+is+not+defined&gs_lcp=CgZwc3ktYWIQAzIFCAAQzQIyBQgAEM0COgcIABBHELADOgcIIxCwAhAnULUwWIk6YOE7aABwAHgAgAG8AYgBzA2SAQQwLjExmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwiThIKH1M7rAhWn7HMBHf4tAY4Q4dUDCA0&uact=5",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 1008,
        "highlighted": false,
        "id": 2187,
        "incognito": false,
        "index": 32,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "KyleADay/react-app-puppeteer: Add Puppeteer to a create-react-app generated app using Jest",
        "url": "https://github.com/KyleADay/react-app-puppeteer",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2190,
        "incognito": false,
        "index": 33,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - Can't run puppeteer in react app, Module not found: Can't resolve 'ws' when compiling - Stack Overflow",
        "url": "https://stackoverflow.com/questions/60700861/cant-run-puppeteer-in-react-app-module-not-found-cant-resolve-ws-when-comp",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2193,
        "incognito": false,
        "index": 34,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome get screenshot of unopened tab - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk00PV_TvfuU7ey28z_0EPQNW_4YvTA%3A1599193763220&ei=o8JRX8OIDdyb4-EPoMKb6A0&q=chrome+get+screenshot+of+unopened+tab&oq=chrome+get+screenshot+of+unopened+tab&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAEyBQghEKABMgUIIRCgATIFCCEQoAE6BwgAEEcQsAM6BAgjECc6BAguECc6BQgAEJECOggIABCxAxCDAToLCC4QsQMQxwEQowI6BQgAELEDOg4ILhCxAxCDARDHARCjAjoHCC4QJxCTAjoKCC4QxwEQrwEQJzoECC4QQzoECAAQQzoHCAAQsQMQQzoCCAA6BggAEBYQHjoICAAQFhAKEB46BAgAEA06CAgAEAgQDRAeOggIIRAWEB0QHjoECCEQFToHCCEQChCgAVDrmgpY-OsKYKLtCmgDcAB4AIAB8QGIAbg0kgEGMS4zNS40mAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwiD5ruB1c7rAhXczTgGHSDhBt0Q4dUDCA0&uact=5",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2205,
        "incognito": false,
        "index": 35,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - Chrome extension-Open the captured screen shot in new tab - Stack Overflow",
        "url": "https://stackoverflow.com/questions/26229882/chrome-extension-open-the-captured-screen-shot-in-new-tab",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2208,
        "incognito": false,
        "index": 36,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - screenshot of all tabs chrome extension - Stack Overflow",
        "url": "https://stackoverflow.com/questions/10602633/screenshot-of-all-tabs-chrome-extension",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.scottlogic.com/sites/default/files/scott-logic-favicon.jpg",
        "height": 1008,
        "highlighted": false,
        "id": 2196,
        "incognito": false,
        "index": 37,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Adding Puppeteer to create-react-app generated projects",
        "url": "https://blog.scottlogic.com/2020/01/22/react-app-puppeteer.html",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2211,
        "incognito": false,
        "index": 38,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - How to launch a new window in Google Chrome Extension - Stack Overflow",
        "url": "https://stackoverflow.com/questions/28799892/how-to-launch-a-new-window-in-google-chrome-extension",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2214,
        "incognito": false,
        "index": 39,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.tabs - Google Chrome",
        "url": "https://developer.chrome.com/extensions/tabs#method-captureVisibleTab",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2257,
        "incognito": false,
        "index": 40,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Declare Permissions - Google Chrome",
        "url": "https://developer.chrome.com/extensions/declare_permissions",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2217,
        "incognito": false,
        "index": 41,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome.windows - Google Chrome",
        "url": "https://developer.chrome.com/extensions/windows#type-CreateType",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2220,
        "incognito": false,
        "index": 42,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome tabs captureVisibletab of minimized window - Google Search",
        "url": "https://www.google.com/search?q=chrome+tabs+captureVisibletab+of+minimized+window&oq=chrome+tabs+captureVisibletab+of+minimized+window&aqs=chrome..69i57j33.14019j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "height": 976,
        "highlighted": false,
        "id": 2250,
        "incognito": false,
        "index": 43,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "New Tab",
        "url": "chrome://newtab/",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2251,
        "incognito": false,
        "index": 44,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "'activeTab' permission is not in effect because this extension has not been in invoked. - Google Search",
        "url": "https://www.google.com/search?q=%27activeTab%27+permission+is+not+in+effect+because+this+extension+has+not+been+in+invoked.&oq=%27activeTab%27+permission+is+not+in+effect+because+this+extension+has+not+been+in+invoked.&aqs=chrome..69i57j0.888j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "height": 1008,
        "highlighted": false,
        "id": 2254,
        "incognito": false,
        "index": 45,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "javascript - Chrome screenshot works only when extension is clicked first - Stack Overflow",
        "url": "https://stackoverflow.com/questions/25964869/chrome-screenshot-works-only-when-extension-is-clicked-first#:~:text=Unchecked%20runtime.-,lastError%20while%20running%20tabs.,a%20click%20on%20your%20extension).",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 1008,
        "highlighted": false,
        "id": 2265,
        "incognito": false,
        "index": 46,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "all_urls permission - Google Search",
        "url": "https://www.google.com/search?q=all_urls+permission&oq=all+urls+permission&aqs=chrome.1.69i57j0l2.4617j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2268,
        "incognito": false,
        "index": 47,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Declare Permissions and Warn Users - Google Chrome",
        "url": "https://developer.chrome.com/extensions/permission_warnings",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/ebcf1b0f/img/favicon_32.png",
        "height": 1008,
        "highlighted": false,
        "id": 2277,
        "incognito": false,
        "index": 48,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "YouTube",
        "url": "https://www.youtube.com/",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": true,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "chrome-extension://nhebkhgegagpgedoofaafhhofmpgdikf/favicon.ico",
        "height": 1008,
        "highlighted": true,
        "id": 2449,
        "incognito": false,
        "index": 49,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": true,
        "status": "complete",
        "title": "React App",
        "url": "chrome-extension://nhebkhgegagpgedoofaafhhofmpgdikf/index.html",
        "width": 1920,
        "windowId": 1
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 143,
        "incognito": false,
        "index": 0,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "turtle nusery rouse hill - Google Search",
        "url": "https://www.google.com/search?q=turtle+nusery+rouse+hill&oq=turtle+nusery+rouse+hill&aqs=chrome..69i57j46.10264j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.turtlenursery.com.au/wp-content/uploads/2017/10/t-logo-100x100.png",
        "height": 981,
        "highlighted": false,
        "id": 149,
        "incognito": false,
        "index": 1,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Paver Supplies | Bricks, Block and Paver Suppliers, Supply in Sydney",
        "url": "https://www.turtlenursery.com.au/bricks-blocks/",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 981,
        "highlighted": false,
        "id": 232,
        "incognito": false,
        "index": 2,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "ProfessorX737/react-sortablejs: A React component built on top of the mature drag and drop library, Sortable.",
        "url": "https://github.com/ProfessorX737/react-sortablejs",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
        "height": 981,
        "highlighted": false,
        "id": 235,
        "incognito": false,
        "index": 3,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "SortableJS/Sortable: Sortable — is a JavaScript library for reorderable drag-and-drop lists on modern browsers and touch devices. No jQuery required. Supports Meteor, AngularJS, React, Polymer, Vue, Ember, Knockout and any CSS library, e.g. Bootstrap.",
        "url": "https://github.com/SortableJS/Sortable",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 350,
        "incognito": false,
        "index": 4,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "chrome take screenshot of webpage react - Google Search",
        "url": "https://www.google.com/search?sxsrf=ALeKk01CiRCnAIv9Lanh4P1hRS20sba3pw%3A1599047641978&ei=2YdPX9GoO5aR9QP4rKS4Dw&q=chrome+take+screenshot+of+webpage+react&oq=chrome+take+screenshot+of+webpage+react&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgATIHCCEQChCgAToHCAAQRxCwAzoGCAAQFhAeOggIIRAWEB0QHlCcUViUVmDnVmgAcAB4AIAB1wKIAc4LkgEFMi0zLjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwiR-bbVtMrrAhWWSH0KHXgWCfcQ4dUDCA0&uact=5",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn.zapier.com/zapier/images/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 353,
        "incognito": false,
        "index": 5,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "How to Take a Full-Page Screenshot",
        "url": "https://zapier.com/blog/full-page-screenshots-in-chrome/",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 356,
        "incognito": false,
        "index": 6,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "📷 How to take a screenshot of a webpage with JavaScript in Node.js (using puppeteer) - DEV",
        "url": "https://dev.to/benjaminmock/how-to-take-a-screenshot-of-a-page-with-javascript-1e7c",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://buddy.works/assets/icons/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 359,
        "incognito": false,
        "index": 7,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "How to take screenshots with Puppeteer | Buddy: The DevOps Automation Platform",
        "url": "https://buddy.works/guides/how-take-screenshots-with-puppeteer-headless-chrome",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 362,
        "incognito": false,
        "index": 8,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer screenshot - Google Search",
        "url": "https://www.google.com/search?q=puppeteer+screenshot&oq=puppeteer+screenshot&aqs=chrome.0.69i59j0l5j69i60l2.2317j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://pptr.dev/favicons/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 365,
        "incognito": false,
        "index": 9,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Browser",
        "url": "https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-class-browser",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico",
        "height": 981,
        "highlighted": false,
        "id": 368,
        "incognito": false,
        "index": 10,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "How to take screenshots using Puppeteer | by Dishant Agnihotri | Medium",
        "url": "https://medium.com/@dishantagnihotri/how-to-take-screenshots-using-puppeteer-79d18157ed0d",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/b8a6decb/img/favicon_32.png",
        "height": 981,
        "highlighted": false,
        "id": 377,
        "incognito": false,
        "index": 11,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer javascript - YouTube",
        "url": "https://www.youtube.com/results?search_query=puppeteer+javascript",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/b8a6decb/img/favicon_32.png",
        "height": 981,
        "highlighted": false,
        "id": 380,
        "incognito": false,
        "index": 12,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Web automation with JavaScript for beginners | Puppeteer - YouTube",
        "url": "https://www.youtube.com/watch?v=wqRKEd0_suw",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.youtube.com/s/desktop/b8a6decb/img/favicon_32.png",
        "height": 981,
        "highlighted": false,
        "id": 383,
        "incognito": false,
        "index": 13,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Automated Form Submissions with Chrome Puppeteer & NodeJS - YouTube",
        "url": "https://www.youtube.com/watch?v=6IOrp8HgnJU",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 386,
        "incognito": false,
        "index": 14,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer embed browser - Google Search",
        "url": "https://www.google.com/search?q=puppeteer+embed+browser&oq=puppeteer+embed+browser&aqs=chrome..69i57.10314j0j7&sourceid=chrome&ie=UTF-8",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
        "height": 981,
        "highlighted": false,
        "id": 389,
        "incognito": false,
        "index": 15,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "puppeteer-extensionbridge - npm",
        "url": "https://www.npmjs.com/package/puppeteer-extensionbridge",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
        "height": 981,
        "highlighted": false,
        "id": 426,
        "incognito": false,
        "index": 16,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "npm",
        "url": "https://www.npmjs.com/~jsoverson",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.gstatic.com/devrel-devsite/prod/v425077d6c7be97246d05a953898cb9591a173a3cef753a451b8729896196bc0a/developers/images/favicon.png",
        "height": 981,
        "highlighted": false,
        "id": 392,
        "incognito": false,
        "index": 17,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Puppeteer  |  Tools for Web Developers  |  Google Developers",
        "url": "https://developers.google.com/web/tools/puppeteer",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": false,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "http://thecodebarbarian.com/favicon.ico",
        "height": 981,
        "highlighted": false,
        "id": 395,
        "incognito": false,
        "index": 18,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": false,
        "status": "complete",
        "title": "Control Chrome from Node.js with Puppeteer | www.thecodebarbarian.com",
        "url": "http://thecodebarbarian.com/control-chrome-from-node-js-with-puppeteer.html",
        "width": 1848,
        "windowId": 144
    },
    {
        "active": true,
        "audible": false,
        "autoDiscardable": true,
        "discarded": false,
        "favIconUrl": "https://www.google.com/images/icons/product/chrome-32.png",
        "height": 981,
        "highlighted": true,
        "id": 457,
        "incognito": false,
        "index": 19,
        "mutedInfo": {
            "muted": false
        },
        "pinned": false,
        "selected": true,
        "status": "complete",
        "title": "Content Scripts - Google Chrome",
        "url": "https://developer.chrome.com/extensions/content_scripts",
        "width": 1848,
        "windowId": 144
    }
]
*/